// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Next.js 관례상 실제 비밀값은 .env.local에 둔다 (dotenv/config 기본값인 .env가 아님).
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
